baseurl = "https://ezhentan.netlify.com/"
languageCode = "en-us"
title = "E-Zhen Tan"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2

[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3

[[menu.main]]
    name = "GitHub-Portfolio"
    url = "https://github.com/ezhentan/schoolprojects"
    weight = 4

[[menu.main]]
    name = "LinkedIn"
    url = "www.linkedin.com/in/ezhentan"
    weight = 5

[params]
    author = "E-Zhen Tan"
    enableGitinfo = true
    enableEmoji = true

    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "IMG_3376.png"

    [params.logo]
    url = "IMG_3376.png"
    width = 50
    height = 50
    alt = "Logo"
